hide_cursor_when_typing: true

font:
  normal:
    family: Hack Nerd Font Mono
    style: Regular
  bold:
    family: Hack Nerd Font Mono
    style: Bold
  italic:
    family: Hack Nerd Font Mono
    style: Italic
  bold_italic:
    family: Hack Nerd Font Mono
    style: Bold Italic
  size: 12

cursor:
  style:
    blinking: Never

# Color schemes
# @ink: https://github.com/alacritty/alacritty/wiki/Color-schemes
# Tested: Sourcerer, Oxide , Tomorrow Night, Gruvbox dark

# Colors (Gruvbox dark customized)
colors:
  # Default colors
  primary:
    background: '#222222'
    foreground: '#c2c2b0'

  # Normal colors
  normal:
    black:   '#222222'
    red:     '#cc241d'
    green:   '#98971a'
    yellow:  '#d79921'
    blue:    '#458588'
    magenta: '#b16286'
    cyan:    '#689d6a'
    white:   '#a89984'

  # Bright colors
  bright:
    black:   '#928374'
    red:     '#fb4934'
    green:   '#b8bb26'
    yellow:  '#fabd2f'
    blue:    '#83a598'
    magenta: '#d3869b'
    cyan:    '#8ec07c'
    white:   '#ebdbb2'
