# Core

[[manager.prepend_keymap]]

on   = [ "!" ]
run  = 'shell "$SHELL" --block --confirm'
desc = "Open shell"

[[manager.prepend_keymap]]
on  = [ "T" ]
run = "plugin --sync max-preview"
desc = "Maximize preview pane"

[[manager.prepend_keymap]]
on  = [ "H" ]
run = "plugin --sync hide-preview"
desc = "Hide preview pane"
