# Core

[[manager.prepend_keymap]]

on   = [ "!" ]
run  = 'shell "$SHELL" --block --confirm'
desc = "Open shell"

[[manager.prepend_keymap]]
on = [ "<C-f>" ]
run = "filter --smart"
desc = "Filter the files"

[[manager.prepend_keymap]]
on  = [ "%", "m"]
run = "plugin --sync max-preview"
desc = "Maximize preview pane"

[[manager.prepend_keymap]]
on  = [ "%", "h" ]
run = "plugin --sync hide-preview"
desc = "Hide preview pane"

# https://github.com/dedukun/bookmarks.yazi

[[manager.prepend_keymap]]
on = [ "m" ]
run = "plugin bookmarks --args=save"
desc = "Save current position as a bookmark"

[[manager.prepend_keymap]]
on = [ "'" ]
run = "plugin bookmarks --args=jump"
desc = "Jump to a bookmark"

[[manager.prepend_keymap]]
on = [ "B", "d" ]
run = "plugin bookmarks --args=delete"
desc = "Delete a bookmark"

[[manager.prepend_keymap]]
on = [ "B", "D" ]
run = "plugin bookmarks --args=delete_all"
desc = "Delete all bookmarks"
