# Core

[[manager.prepend_keymap]]

on   = [ "!" ]
run  = 'shell "$SHELL" --block --confirm'
desc = "Open shell"

[[manager.prepend_keymap]]
on = [ "<C-f>" ]
run = "filter --smart"
desc = "Filter the files"

[[manager.prepend_keymap]]
on  = [ "%", "m"]
run = "plugin --sync max-preview"
desc = "Maximize preview pane"

[[manager.prepend_keymap]]
on  = [ "%", "h" ]
run = "plugin --sync hide-preview"
desc = "Hide preview pane"

# https://github.com/DreamMaoMao/keyjump.yazi

[[manager.prepend_keymap]]
on   = [ "f" ]
run  = "plugin keyjump"
desc = "Keyjump (Normal mode)"

[[manager.prepend_keymap]]
on   = [ "F" ]
run  = "plugin keyjump --args=global"
desc = "Keyjump (Global mode)"

[[manager.prepend_keymap]]
on   = [ "@", "k" ]
run  = "plugin keyjump --args=keep"
desc = "Keyjump (Keep mode)"

[[manager.prepend_keymap]]
on   = [ "@", "s" ]
run  = "plugin keyjump --args=select"
desc = "Keyjump (Select mode)"

[[manager.prepend_keymap]]
on   = [ "@", "g" ]
run  = "plugin keyjump --args='global once'"
desc = "Keyjump (once Global mode)"

# https://github.com/dedukun/bookmarks.yazi

[[manager.prepend_keymap]]
on = [ "m" ]
run = "plugin bookmarks --args=save"
desc = "Save current position as a bookmark"

[[manager.prepend_keymap]]
on = [ "'" ]
run = "plugin bookmarks --args=jump"
desc = "Jump to a bookmark"

[[manager.prepend_keymap]]
on = [ "B", "d" ]
run = "plugin bookmarks --args=delete"
desc = "Delete a bookmark"

[[manager.prepend_keymap]]
on = [ "B", "D" ]
run = "plugin bookmarks --args=delete_all"
desc = "Delete all bookmarks"
