# Core

[[manager.prepend_keymap]]

on   = [ "!" ]
run  = 'shell "$SHELL" --block --confirm'
desc = "Open shell"

[[manager.prepend_keymap]]
on = [ "<C-f>" ]
run = "filter --smart"
desc = "Filter the files"

[[manager.prepend_keymap]]
on  = [ "%", "m"]
run = "plugin --sync max-preview"
desc = "Maximize preview pane"

[[manager.prepend_keymap]]
on  = [ "%", "h" ]
run = "plugin --sync hide-preview"
desc = "Hide preview pane"

