# https://alacritty.org/config-alacritty.html

import = [
    "~/.config/alacritty/theme.toml",
    "~/.config/alacritty/font.toml"
]

[shell]
args = ["--login"]
program = "/bin/zsh"

[env]
TERM = "xterm-256color"

[cursor.style]
blinking = "Never"

[mouse]
hide_when_typing = true
